virt:
  box: peru/ubuntu-20.04-server-amd64

env_common:
  ostype: linux
  arch: amd64
  assets: /tmp/assets
  domain: .example.com
  datadisk: /dev/vdb

services:
  nexus:
    ip: 192.168.122.100
    ports:
      apt:        8081
      dockerhub:  5000
  rke2:
    release: latest
    cni: canal      # canal(default)|cilium|core|harvester|multus|vsphere
  helm:
    release: latest

nodes:
  - name: srv
    type: server
    mem: 10240
    cpus: 3
    data: 10G
    interfaces:
      - ip: 192.168.122.220
        auto_config: "True"
        network_name: default
        method: static
        type: private_network
      - ip: 192.168.123.20
        auto_config: "True"
        network_name: "Instances Network"
        method: static
        type: private_network

  - name: a01
    type: agent
    mem: 10240
    cpus: 3
    data: 10G
    interfaces:
      - ip: 192.168.122.221
        auto_config: "True"
        network_name: default
        method: static
        type: private_network
      - ip: 192.168.123.21
        auto_config: "True"
        network_name: "Instances Network"
        method: static
        type: private_network