image:
  repository: scylladb
  pullPolicy: IfNotPresent
  tag: ""
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi
webhook:
  createSelfSignedCertificate: false
  certificateSecretName:  scylla-operator-serving-cert
