apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylla-manager-pv1-srv
  namespace: scylla-manager
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /kube-data-scylla-manager
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - srv.example.com